import type { ToolDefinition } from '../types.js';
import * as toolInputSchemas from '../schemas/toolInputSchemas.js';

const rawTools: Omit<ToolDefinition, 'inputSchema'>[] = [
  {
    name: 'COUNT_auth_status',
    title: 'COUNT Auth Status',
    description: 'Return the MCP server authentication configuration state without exposing secrets.',
    method: 'GET',
    pathTemplate: '/__local/auth-status',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_describe_endpoint',
    title: 'Describe COUNT Tool',
    description:
      'Return human-readable guidance for a specific COUNT tool, including the partner API path it wraps, expected query/body fields from the public COUNT developer documentation, and tips for which IDs to pass. Useful for checking request shape before unfamiliar create/update operations.',
    method: 'GET',
    pathTemplate: '/__local/describe-endpoint',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_knowledge',
    title: 'COUNT Knowledge',
    description:
      'COUNT connector and workflow FAQ — call this for “how do I…?” questions before guessing. Covers: authorizing additional workspaces (disconnect + reconnect), Claude/ChatGPT reconnect steps, multiple workspace usage, why auth_status may show fewer workspaces than the COUNT web app, external UUID conventions, P&L category filters (e.g. shipping/Freight & Courier), and bulk import batch sizes. Optional input: `topic` (FAQ id) or `search` (free text). Omit both to list all topics with summaries.',
    method: 'GET',
    pathTemplate: '/__local/knowledge',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_playbooks',
    title: 'COUNT Playbooks',
    description:
      'End-to-end accounting workflows with ordered steps and tool names. Call before multi-step tasks such as paying a vendor bill, creating and sending an invoice, bulk migration imports, or month-end review. Optional input: `playbook` (id) or `search` (free text). Omit both to list all playbooks with summaries. Playbook ids: pay_vendor_bill, create_invoice_and_send, migration_import, budget_import, month_end_review.',
    method: 'GET',
    pathTemplate: '/__local/playbooks',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_resolve_references',
    title: 'Resolve Name References',
    description:
      'Resolve human-readable vendor, customer, account, project, or tag names to external COUNT UUIDs for this workspace. Pass one or more name fields; each returns uuid, matchConfidence (exact/fuzzy/ambiguous/not_found), and candidates when ambiguous. Use before bulk imports instead of guessing UUIDs from large list results.',
    method: 'GET',
    pathTemplate: '/__local/resolve-references',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_validate_payload',
    title: 'Validate Payload',
    description:
      'Preflight validation for partner API tool payloads — no data is written. Runs typed schema validation on query and body, bulk batch size (cap 100), legacy numeric field rejection, and required fields for bulk create and create_bill. Set verifyReferences: true to confirm UUIDs exist in the workspace. Works for list and mutation tools.',
    method: 'GET',
    pathTemplate: '/__local/validate-payload',
    requiresUserAuth: false,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_refresh_access_token',
    title: 'Refresh COUNT Access Token',
    description:
      'Refresh the COUNT partner access token using the configured refresh token. The refreshed token is kept in this MCP process memory.',
    method: 'POST',
    pathTemplate: '/partners/refresh-user-access-token',
    requiresUserAuth: false,
    readOnly: false,
    destructive: false,
    idempotent: false,
  },
  {
    name: 'COUNT_list_transactions',
    title: 'List Transactions',
    description:
      'List register/bank transactions for the authenticated workspace. Returns transaction rows with `id` as the external UUID — pass that UUID to update/change-category/delete tools. Filter fields are documented on the `query` input schema.',
    method: 'GET',
    pathTemplate: '/partners/transactions',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_transaction',
    title: 'Get Transaction',
    description:
      'Get a single transaction by external UUID. Returns transactions hidden from the workspace UI as well. Optional `query` fields are forwarded as Sequelize `include` directives to expand related entities (e.g. category, vendor, customer, tags, taxes). Use the returned `id` (the external UUID) as the next call argument for `update_transaction`, `change_transaction_category`, or `delete_transaction`.',
    method: 'GET',
    pathTemplate: '/partners/transactions/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_transaction',
    title: 'Create Transaction',
    description:
      'Create a register/bank transaction in the authenticated COUNT workspace. **Set the category, vendor/customer, project, tags, and taxes in this single call — do NOT follow up with `change_transaction_category` when you already know the category at creation time.** The create endpoint resolves the category UUID, posts the journal entries, and writes tax associations atomically. Required body: `accUuid` (account UUID from `list_accounts` — the bank/cash account the money moves through), `amount` (positive decimal — see sign convention below), and either `postedDate` or `date` (YYYY-MM-DD). Optional body: `description`, `currency`, `type` (`Expense` | `Income` | `Transfer` | `Journal Entry` — case-sensitive, but lowercase `expense`/`income`/`transfer`/`journal`/`journal_entry` are also accepted and normalized server-side), `categoryAccountUuid` (income/expense category — same UUID source as `accUuid`; **set this here at creation, no separate `change_transaction_category` call needed**), `vendorUuid`, `customerUuid`, `projectUuid`, `tagUuids: string[]`, `taxes: number[]` (numeric internal tax ids — taxes are not yet UUID-resolved on the partner API), `notes`, `authorizedDate`. **Sign convention**: pass `amount` as a positive number; the server flips the sign for income internally. **Type omission**: when `type` is not sent, the server infers it from the category-account type. **FK resolution**: `vendorUuid`/`customerUuid`/`projectUuid`/`tagUuids` are resolved into the internal numeric ids the service expects; do not send `vendorId`/`customerId`/`projectId`/`tags` numeric arrays unless you really do have internal ids. **Use `change_transaction_category` only to modify the category on an EXISTING transaction.**',
    method: 'POST',
    pathTemplate: '/partners/transactions',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_bulk_create_transactions',
    title: 'Bulk Create Transactions',
    description:
      'Create up to 100 register/bank transactions in a single call. Body: `{ "transactions": [<row>, ...] }` where each `<row>` uses the EXACT same shape as `COUNT_create_transaction` (required `accUuid`, `amount`, `postedDate`/`date`; optional `description`, `currency`, `type`, `categoryAccountUuid`, `vendorUuid`, `customerUuid`, `projectUuid`, `tagUuids: string[]`, `taxes: number[]`, `notes`, `authorizedDate`). **Set the category, vendor/customer, project, tags, and taxes ON EACH ROW in this single call — no follow-up `change_transaction_category` needed.** **Partial-success contract**: each row runs in its own DB transaction; one row failing never rolls back another row\'s writes. Response envelope: `{ "successCount": N, "errorCount": M, "results": [{ "index": 0, "success": true, "transaction": {...} } | { "index": 1, "success": false, "error": "..." }, ...] }` — read `errorCount` first; if non-zero, iterate `results` and only retry the rows where `success: false`. The HTTP status is always `201` when the batch was accepted, even if all rows failed. **Cap**: 100 rows per call (split larger imports into multiple calls). **Recommended batch size**: ~25 rows for large historical imports (e.g. billing-system backfills); larger batches increase timeout risk. **Use cases**: ingest a CSV of bank transactions, replay a missed sync window, backfill historical activity. For a single transaction, prefer `COUNT_create_transaction` — the response shape is simpler.',
    method: 'POST',
    pathTemplate: '/partners/transactions/bulk',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_transaction',
    title: 'Update Transaction',
    description:
      'Update non-category fields on an EXISTING transaction by external UUID. Body fields: `vendorUuid`, `customerUuid`, `projectUuid`, `tagUuids: string[]` (replaces all tags — `[]` clears them), plus regular safe Transaction columns (`description`, `notes`, `amount`, `postedDate`, `authorizedDate`, etc.). Do not send `categoryAccountUuid` or `categoryAccountId` here; use `COUNT_change_transaction_category` to change/clear the category on an existing transaction so taxes, transfers, fixed assets, and journal side effects run through the accounting workflow. (When CREATING a new transaction, pass `categoryAccountUuid` directly to `COUNT_create_transaction` — no follow-up call is needed.) The response includes `_partnerWarnings: [{ field, reason, message }]` when fields you sent were ignored (`reason: "internal_only"` for fields managed internally — e.g. `linkedTransferTransactionId`, `providerTransactionId`, `billId`; `reason: "unknown_field"` for typos / fields not on the transaction model).',
    method: 'PATCH',
    pathTemplate: '/partners/transactions/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_change_transaction_category',
    title: 'Change Transaction Category',
    description:
      'Change, clear, or transfer-link the category (GL account) on an EXISTING transaction by external UUID. **Use this tool only when modifying the category of a transaction that already exists.** When creating a NEW transaction, pass `categoryAccountUuid` directly to `COUNT_create_transaction` instead — the create endpoint resolves the category, posts the journal entries, and writes tax associations in a single call (no follow-up `change_transaction_category` is needed). Body: `categoryAccountUuid` (the `id`, `accUuid`, or `accountUuid` of the target account from `list_accounts`); pass `null` to uncategorize. Optional body fields: `notes`, `taxes`, `autoCreateMatching`, `autoReview`, `linkedTransferTransactionUuid` (or UUID-shaped `linkedTransferTransactionId` from `list_transactions`), `fixedAssetAssignment`. The category-change workflow ensures taxes, transfers, fixed assets, and journal side effects all stay in sync on existing rows.',
    method: 'PATCH',
    pathTemplate: '/partners/transactions/{id}/change-category',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_assign_transaction_to_bills_invoices',
    title: 'Assign Transaction To Bills Or Invoices',
    description:
      'Apply an existing bank/expense/income transaction as payment against one or more invoices or bills. URL `{id}` is the transaction UUID from `list_transactions`. Body: `{ matchingType: "invoice" | "bill", records: [{ id: <invoice or bill UUID>, paymentAmount: <decimal>, notes?: string }], withCaution?: boolean, parentCategoryAccountUuid?: string }`. For invoices use `matchingType: "invoice"` with an **Income** transaction (bank deposit); invoice refunds use **Expense**. For bills use `matchingType: "bill"` with an **Expense** transaction (vendor payment); vendor memos use **Income**. `paymentAmount` must not exceed the document open balance; partial payments may split the transaction. Optional `parentCategoryAccountUuid` sets the category for any remainder when the payment is less than the transaction amount. Do not set `invoiceId` / `billId` on transaction update — use this endpoint instead.',
    method: 'POST',
    pathTemplate: '/partners/transactions/{id}/assign-to-bills-invoices',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_transaction',
    title: 'Delete Transaction',
    description: 'Delete a transaction by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/transactions/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_account_sub_types',
    title: 'List Account Sub-Types',
    description:
      'List every chart-of-accounts sub-type available in COUNT (global catalog — the same integer ids apply in every workspace). **Call this before `COUNT_create_account`** to discover the correct `subTypeId`; e.g. set `query.type` to `"Liabilities"` and pick the row whose `name` is `Credit Card`. Optional `query.type`: one of `Assets`, `Liabilities`, `Equity`, `Income`, `Expenses` (case-sensitive, plural). Each row returns `id` (pass as `subTypeId` on create), `type`, `name`, `description`, and `anchorTier`. **Never guess or sequentially probe subType ids** — they are sparse and not predictable from other ids.',
    method: 'GET',
    pathTemplate: '/partners/account-sub-types',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_accounts',
    title: 'List Chart Of Accounts',
    description:
      'List chart of accounts for the authenticated COUNT workspace. When you need a `subTypeId` for a **new** account and no similar account exists yet, prefer `COUNT_list_account_sub_types` instead of guessing from sparse ids. Optional filters (pass under `query`): `type` must be one of `Assets`, `Liabilities`, `Equity`, `Income`, `Expenses` (case-sensitive, plural — singular forms like "Asset" are rejected); `subTypeId` is a positive integer; `search` is a substring matched against account name / number; boolean-string filters `inactive`, `includeBalances`, `includeHidden`, `includeHiddenAccounts`, `is1099Box`, `notAssignedToReporter`, `onlyCategoryAccounts`, `includeDeleteMeta` accept `"true"` / `"false"`. Existing rows include `subType.id` — you may reuse that integer when creating another account in the same bucket.',
    method: 'GET',
    pathTemplate: '/partners/chart-of-accounts',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_account',
    title: 'Create Account',
    description:
      'Create a chart-of-accounts entry. **Always resolve `subTypeId` first — never guess or probe ids.** Preferred: `COUNT_list_account_sub_types` (filter `query.type`, pick the matching `name`, use its `id`). Fallback: `COUNT_list_accounts` with `query.type` and reuse `subType.id` from an existing row in that bucket. Required body: `name` (string) and `subTypeId` (integer from list_account_sub_types or list_accounts). Optional body: `accountNumber`, `currency` (defaults to the workspace currency), `description`, `color` (hex), `parentAccountId` (numeric id of an existing parent account — sub-accounts inherit the parent\'s `type` / `currency` / `status` and a sub-account cannot itself have sub-accounts), `institutionId`, `taxes: number[]` (internal numeric tax ids — required for NZ workspaces), `status` ("active" | "inactive"). The high-level `type` (Assets/Liabilities/Equity/Income/Expenses) is derived from `subTypeId` server-side; do not send it. If creation fails, tell the user COUNT could not create the account and include the `requestId` when present — **never** quote stack traces, source file paths, line numbers, or internal database field names in user-visible text.',
    method: 'POST',
    pathTemplate: '/partners/chart-of-accounts',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_account',
    title: 'Update Account',
    description:
      'Update a chart-of-accounts entry by external UUID. Pass only the fields you want to change. Editable: `name`, `accountNumber`, `description`, `color`, `status` ("active" | "inactive"), `subTypeId` (must keep the same high-level `type` — switching a Bank account into an Income sub-type is rejected), `parentAccountId` (set to a valid parent id to nest, or pass `isChildAccount: false` to detach), `connectionSyncEnabled` (only meaningful on connected feed accounts). Do not send `type` (derived from `subTypeId`), `teamId`, `connectionId`, or `systemCreated` — they are stripped. System / non-editable accounts (e.g. payroll defaults) accept only a small allowlist of cosmetic fields plus name on physical accounts; expect a 403 if you try to edit a protected field. An empty body returns 400.',
    method: 'PATCH',
    pathTemplate: '/partners/chart-of-accounts/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_account',
    title: 'Delete Account',
    description: 'Delete a chart of accounts entry by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/chart-of-accounts/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_vendors',
    title: 'List Vendors',
    description: 'List vendors for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/vendors',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_vendor',
    title: 'Create Vendor',
    description: 'Create a vendor.',
    method: 'POST',
    pathTemplate: '/partners/vendors',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_vendor',
    title: 'Update Vendor',
    description: 'Update a vendor by external UUID.',
    method: 'PATCH',
    pathTemplate: '/partners/vendors/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_vendor',
    title: 'Delete Vendor',
    description: 'Delete a vendor by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/vendors/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_customers',
    title: 'List Customers',
    description: 'List customers for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/customers',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_customer',
    title: 'Get Customer',
    description: 'Get a customer by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/customers/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_customer',
    title: 'Create Customer',
    description:
      'Create a customer. Required body: `customer` (business or person name). Optional body: `email`, `mainPhone`, `website`, `notes`, `status` (`active` | `inactive`), `paymentTerm`, `taxNumber`, `taxAutoCalculate`, `taxExcluded`, `taxes` (numeric tax ids), `billingAddress`, `shippingAddress`, `contacts: [{ firstName?, lastName?, email?, phone?, isPrimary? }]`. Returns 201 with the created customer; `id` in the response is the external UUID.',
    method: 'POST',
    pathTemplate: '/partners/customers',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_customer',
    title: 'Update Customer',
    description: 'Update a customer by external UUID.',
    method: 'PUT',
    pathTemplate: '/partners/customers/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_bulk_create_customers',
    title: 'Bulk Create Customers',
    description:
      'Create up to 100 customers in a single call. Body: `{ "customers": [<row>, ...] }` where each `<row>` uses the EXACT same shape as `COUNT_create_customer` (required `customer`; optional `email`, `mainPhone`, `website`, `notes`, `status`, `paymentTerm`, `taxNumber`, `taxAutoCalculate`, `taxExcluded`, `taxes`, `billingAddress`, `shippingAddress`, `contacts`). **Partial-success contract**: each row runs in its own DB transaction; one row failing never rolls back another row\'s writes. Response envelope: `{ "successCount": N, "errorCount": M, "results": [{ "index": 0, "success": true, "customer": {...} } | { "index": 1, "success": false, "error": "..." }, ...] }` — read `errorCount` first; if non-zero, iterate `results` and only retry the rows where `success: false`. The HTTP status is always `201` when the batch was accepted, even if all rows failed. **Cap**: 100 rows per call. **Recommended batch size**: ~25 rows for large migrations (e.g. importing customers from an external billing system).',
    method: 'POST',
    pathTemplate: '/partners/customers/bulk',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_bulk_update_customers',
    title: 'Bulk Update Customers',
    description:
      'Update up to 100 customers in a single call. Body: `{ "customers": [{ "uuid": "<external COUNT customer id>", ...fields }] }` where each row must include `uuid` plus the fields to patch (same writable fields as `COUNT_update_customer`, e.g. `email`, `mainPhone`, `website`, `notes`, `status`, `paymentTerm`, `billingAddress`, `shippingAddress`, `contacts`). **Partial-success contract**: each row is updated independently; one row failing never rolls back another row\'s writes. Response envelope: `{ "successCount": N, "errorCount": M, "results": [{ "index": 0, "success": true, "customer": {...} } | { "index": 1, "success": false, "error": "..." }, ...] }`. The HTTP status is always `201` when the batch was accepted. **Recommended batch size**: ~25 rows for backfilling email/phone on migrated customers.',
    method: 'PATCH',
    pathTemplate: '/partners/customers/bulk',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_customer',
    title: 'Delete Customer',
    description: 'Delete a customer by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/customers/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_people',
    title: 'List People',
    description: 'List people records for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/people',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_person',
    title: 'Get Person',
    description: 'Get a people record by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/people/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_products',
    title: 'List Products',
    description: 'List products and services for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/products',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_product',
    title: 'Get Product',
    description: 'Get a product or service by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/products/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_product',
    title: 'Create Product',
    description:
      'Create a product or service. Use `categoryAccountUuid` and `purchaseCategoryAccountUuid` (from `list_accounts`) for income/purchase category accounts — do not pass UUID-shaped values in `categoryAccountId`/`purchaseCategoryAccountId`. Use `taxUuids` (from `list_taxes`) for taxes.',
    method: 'POST',
    pathTemplate: '/partners/products',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_product',
    title: 'Update Product',
    description:
      'Update a product or service by external UUID. Use `categoryAccountUuid`, `purchaseCategoryAccountUuid`, and `taxUuids` for account/tax references (see `COUNT_create_product`).',
    method: 'PATCH',
    pathTemplate: '/partners/products/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_product',
    title: 'Delete Product',
    description: 'Delete a product or service by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/products/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_tags',
    title: 'List Tags',
    description: 'List tags for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/tags',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_tag',
    title: 'Get Tag',
    description: 'Get a tag by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/tags/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_tag',
    title: 'Create Tag',
    description: 'Create a tag.',
    method: 'POST',
    pathTemplate: '/partners/tags',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_tag',
    title: 'Update Tag',
    description: 'Update a tag by external UUID.',
    method: 'PATCH',
    pathTemplate: '/partners/tags/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_tag',
    title: 'Delete Tag',
    description: 'Delete a tag by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/tags/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_tag_groups',
    title: 'List Tag Groups',
    description: 'List tag groups for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/tags/groups',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_tag_group',
    title: 'Get Tag Group',
    description: 'Get a tag group by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/tags/groups/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_tag_group',
    title: 'Create Tag Group',
    description:
      'Create a tag group. Body: `name` (required, string, unique per workspace), `color` (optional string), and `tagUuids` (optional array of tag UUIDs from `list_tags`) — each tag may belong to at most one group, so passing a tag already in another group rejects the request with a 400. Send tag UUIDs (not numeric ids); the server resolves them to internal ids automatically.',
    method: 'POST',
    pathTemplate: '/partners/tags/groups',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_tag_group',
    title: 'Update Tag Group',
    description:
      'Update a tag group by external UUID. Body: optional `name`, `color`, and `tagUuids` (array of tag UUIDs from `list_tags`). When `tagUuids` is sent the group\'s membership is REPLACED with that exact set (existing tags not in the array are removed, new ones added); pass `[]` to clear all tags. A tag can only belong to one group at a time. Send tag UUIDs (not numeric ids); the server resolves them to internal ids automatically.',
    method: 'PATCH',
    pathTemplate: '/partners/tags/groups/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_tag_group',
    title: 'Delete Tag Group',
    description: 'Delete a tag group by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/tags/groups/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_invoices',
    title: 'List Invoices',
    description: 'List invoices for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/invoices',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_invoice',
    title: 'Get Invoice',
    description: 'Get an invoice by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/invoices/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_invoice',
    title: 'Create Invoice',
    description:
      'Create an invoice, credit memo, or estimate. Required body: `customerUuid` (from `list_customers`), `date` (YYYY-MM-DD), and `products: [{ productUuid | uuid, quantity, unitPrice, ... }]` (each line resolves a product UUID into the internal product id; `unitPrice` is per-unit in workspace currency). Optional body: `invoiceType` ("invoice" — default | "estimate" | "memo"), `invoiceNumber`, `dueDate` (YYYY-MM-DD), `currency` (defaults to workspace currency), `discount` + `discountDescription`, `notes`, `tagUuids: string[]` (replaces all tags), `appliedToInvoiceUuid` (only for `invoiceType: "memo"` — links the credit memo to the original invoice), `isDraft` (boolean — drafts skip approval / journals), `applyCredit` + `creditMemo: { id, amount }` (apply an existing memo), and recurring-template fields (`recurrencePattern`, `inAdvanceCreationDays`) when creating a recurring schedule via this endpoint. **Do not send numeric ids for `customer`/`products[].id`/`tags`/`appliedToInvoiceId`** — the partner middleware resolves UUIDs into them. Memos cannot be recurring; recurring memos return 400.',
    method: 'POST',
    pathTemplate: '/partners/invoices',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_invoice',
    title: 'Update Invoice',
    description:
      'Update an invoice by external UUID. Pass only the fields you want to change. ' +
      'Lifecycle/state fields (`paymentStatus`, `isSent`, `approved`, `total`, `isDeleted`, `teamId`) are managed internally and cannot be set here — use the dedicated endpoints (e.g. /approve, /send, /apply-multiple-credit-to-invoice) instead. ' +
      'When the body is empty or contains internal-only or unknown fields, the response is still 200 with the unchanged invoice but includes a `_partnerWarnings: [{ field, reason, message }]` array describing each ignored field — read it before assuming the update succeeded.',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_invoice',
    title: 'Delete Invoice',
    description: 'Delete an invoice by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/invoices/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_approve_invoice',
    title: 'Approve Invoice',
    description:
      'Approve a draft invoice by external UUID. Moves the invoice from `draft` → `approved`, posts the underlying journal entries, and makes the invoice eligible for `send`. Body is optional — pass nothing for the standard approval. Errors with 400 if the invoice is already approved, sent, or paid; not valid for `invoiceType: "memo"` drafts (use the regular update + send flow on memos).',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}/approve',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_send_invoice',
    title: 'Send Invoice',
    description:
      'Send (or re-send) an approved invoice to its customer by external UUID. Optional body: `recipients: string[]` (override the customer\'s default email), `subject`, `message`, `attachPdf: boolean` (defaults to true), `cc: string[]`, `bcc: string[]`. The invoice must be approved first via `approve_invoice`; calling `send` on a draft returns 400. After a successful send the invoice transitions to `sent`/`unpaid` and becomes the canonical version the customer sees in the public link.',
    method: 'POST',
    pathTemplate: '/partners/invoices/{id}/send',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_get_invoice_public_link',
    title: 'Get Invoice Public Link',
    description: 'Get a public payment/view link for an invoice by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/invoices/{id}/public-link',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_invoice_audit_log',
    title: 'Get Invoice Audit Log',
    description: 'Get the audit log for an invoice by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/invoices/{id}/audit-log',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_add_invoice_attachments_from_urls',
    title: 'Add Invoice Attachments From URLs',
    description:
      'Attach documents to an invoice (or estimate / memo) by external UUID using already-hosted URLs — the COUNT server fetches each URL once and stores it as a regular invoice attachment. Body: `{ attachments: [{ url: string, title?: string }] }`. The URL must be publicly fetchable from the COUNT server (no signed-cookie / VPN-only links). For uploading raw bytes use the dedicated `/attachments/upload` multipart endpoint instead — that path is not exposed as an MCP tool because MCP tools cannot send multipart bodies.',
    method: 'POST',
    pathTemplate: '/partners/invoices/{id}/attachments',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_apply_multiple_credits_to_invoice',
    title: 'Apply Multiple Credits To Invoice',
    description:
      'Apply one or more credit memos to a single invoice by external UUID. Body: `{ creditMemos: [{ id: <invoice or memo UUID>, amount: <decimal> }, ...] }`. Each `id` accepts a UUID, a numeric id, or a numeric string — the partner middleware resolves them and asserts each memo belongs to the same workspace. The sum of `amount` values cannot exceed the open balance of the target invoice or the available balance on the memos; the request rolls back atomically if any memo is over-applied.',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}/apply-multiple-credit-to-invoice',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_apply_credit_to_multiple_invoices',
    title: 'Apply Credit To Multiple Invoices',
    description:
      'Apply a single credit memo (the URL `id`) across multiple target invoices in one call. Body: `{ invoices: [{ id: <invoice UUID or numeric id>, amount: <decimal> }, ...] }`. The URL `id` is the credit memo to draw from; each entry in `invoices` is a target invoice plus the dollar amount of the memo to apply to it. Total applied amount cannot exceed the memo\'s remaining balance. The partner middleware resolves UUIDs to numeric ids and rejects cross-workspace references with 404.',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}/apply-credit-to-multiple-invoices',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_remove_invoice_credit',
    title: 'Remove Invoice Credit',
    description:
      'Remove a previously-applied credit memo from an invoice by external UUID. Body: `{ memoId: <credit memo UUID or numeric id> }`. The memo\'s balance is restored and the target invoice\'s open balance increases by the unapplied amount. 404 if the memo isn\'t currently applied to this invoice.',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}/remove-credit',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_remove_invoice_transaction',
    title: 'Remove Invoice Transaction Payment',
    description:
      'Remove a previously-applied transaction payment from an invoice by external UUID. Body: `{ transactionId: <transaction UUID from list_transactions>, withCaution?: boolean }`. Restores the invoice open balance and unlinks the transaction from Accounts Receivable. Manual payment links only — automated Stripe links may not be removable via this endpoint.',
    method: 'PATCH',
    pathTemplate: '/partners/invoices/{id}/remove-transaction',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_list_recurring_invoice_templates',
    title: 'List Recurring Invoice Templates',
    description: 'List recurring invoice templates for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/recurring-invoice-templates',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_recurring_invoice_template',
    title: 'Get Recurring Invoice Template',
    description: 'Get a recurring invoice template by external UUID.',
    method: 'GET',
    pathTemplate: '/partners/recurring-invoice-templates/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_recurring_invoice_template',
    title: 'Create Recurring Invoice Template',
    description:
      'Create a recurring invoice template. Same body shape as `create_invoice` (`customerUuid`, `products`, etc.) PLUS a required `recurrencePattern` object describing the cadence (e.g. monthly, weekly). Optional `inAdvanceCreationDays` controls how many days before each scheduled date the next invoice instance is generated. `invoiceType` defaults to "invoice"; "memo" is rejected (credit memos cannot recur). `isDraft` defaults to true so the template is paused until you explicitly resume it via `resume_recurring_invoice_template`.',
    method: 'POST',
    pathTemplate: '/partners/recurring-invoice-templates',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_recurring_invoice_template',
    title: 'Update Recurring Invoice Template',
    description: 'Update a recurring invoice template by external UUID.',
    method: 'PATCH',
    pathTemplate: '/partners/recurring-invoice-templates/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_recurring_invoice_template',
    title: 'Delete Recurring Invoice Template',
    description: 'Delete a recurring invoice template by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/recurring-invoice-templates/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_pause_recurring_invoice_template',
    title: 'Pause Recurring Invoice Template',
    description: 'Pause a recurring invoice template by external UUID.',
    method: 'POST',
    pathTemplate: '/partners/recurring-invoice-templates/{id}/pause',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_resume_recurring_invoice_template',
    title: 'Resume Recurring Invoice Template',
    description: 'Resume a recurring invoice template by external UUID.',
    method: 'POST',
    pathTemplate: '/partners/recurring-invoice-templates/{id}/resume',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_list_bills',
    title: 'List Bills',
    description:
      'List vendor bills for the authenticated workspace. Returns bill rows with `id` as the external UUID. Filter fields are documented on the `query` input schema.',
    method: 'GET',
    pathTemplate: '/partners/bills',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_bill',
    title: 'Get Bill',
    description:
      'Get a single bill by external UUID. Returns the bill record with line items, attachments, payments, current approval/payment status, and the linked vendor. Note: this endpoint also returns soft-deleted bills, so check the `isDeleted` field on the response if you need to filter them out client-side.',
    method: 'GET',
    pathTemplate: '/partners/bills/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_bill',
    title: 'Create Bill',
    description:
      'Create a vendor bill (accounts payable). Required body: `vendorUuid` (vendor UUID from `list_vendors`), `date` (YYYY-MM-DD), `dueDate` (YYYY-MM-DD), and `lineItems: [{ categoryAccountUuid, description?, quantity, price, total?, taxes?, projectUuid?, customerUuid? }]` where `categoryAccountUuid` is the expense/category account UUID from `list_accounts`. Optional body: `billNumber`, `purchaseOrderNumber`, `notes`, `currency` (defaults to workspace currency), `attachments: [{ url, title? }]`, `tagUuids: string[]`, `projectUuid`. Do NOT send numeric `vendorId`, `categoryAccountId`, or `tags` — use UUID fields only. The created bill enters the `draft` state; call `approve_bill` to post journals and make it eligible for payment. Returns 201 with the bill, or a `{ statusCode, message }` error envelope on validation failure.',
    method: 'POST',
    pathTemplate: '/partners/bills',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_bill',
    title: 'Update Bill',
    description:
      'Update a bill by external UUID. Pass only the fields you want to change. Editable: `vendorUuid`, `date`, `dueDate`, `billNumber`, `purchaseOrderNumber`, `notes`, `currency`, `lineItems` (replaces all lines when provided; each line uses `categoryAccountUuid`, `quantity`, `price`, optional `projectUuid`, `customerUuid`), `tagUuids`, `projectUuid`, `attachments`. Do NOT send numeric `vendorId`, `categoryAccountId`, or `tags`. Approved/paid bills have a more restrictive editable set — expect 400 on date/line changes after approval; use `delete_bill` + recreate if you need a structural change post-approval.',
    method: 'PATCH',
    pathTemplate: '/partners/bills/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_bill',
    title: 'Delete Bill',
    description:
      'Delete a bill by external UUID. Soft-delete on draft bills; bills that have any payments applied (`paidAmount > 0`) cannot be deleted and return 400 — unapply payments first via the standard payment endpoints.',
    method: 'DELETE',
    pathTemplate: '/partners/bills/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_approve_bill',
    title: 'Approve Bill',
    description:
      'Approve a draft bill by external UUID. Posts the underlying journal entries (debit each line\'s expense account, credit Accounts Payable) and makes the bill eligible for payment. Body is optional. Errors with 400 if the bill is already approved or has no line items.',
    method: 'POST',
    pathTemplate: '/partners/bills/{id}/approve',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_apply_vendor_memos_to_bill',
    title: 'Apply Vendor Memos To Bill',
    description:
      'Apply one or more vendor credit memos toward an approved bill by external UUID. Body: `{ memosBills: [{ id: <vendor-memo bill UUID from list_bills with billType vendor_memo>, amount: <decimal> }, ...] }`. Each memo must belong to the same vendor as the target bill; total applied cannot exceed the bill open balance or memo available balance. Vendor memos are bill records with `billType: "vendor_memo"` — use their UUID as `id`.',
    method: 'POST',
    pathTemplate: '/partners/bills/{id}/apply-vendor-memos',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_unassign_bill_transaction',
    title: 'Unassign Bill Transaction Payment',
    description:
      'Remove a previously-applied transaction payment from a bill by external UUID. Body: `{ transactionId: <transaction UUID from list_transactions>, withCaution?: boolean }`. Restores the bill open balance and clears the transaction\'s bill link.',
    method: 'POST',
    pathTemplate: '/partners/bills/{id}/unassign-transaction',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_list_journal_entries',
    title: 'List Journal Entries',
    description: 'List journal entries for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/journal-entries',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_journal_entry',
    title: 'Create Journal Entry',
    description:
      'Create a manual journal entry. Body: required `descriptionEntry` (memo), `date` (YYYY-MM-DD), and `lines` (array). Each line needs `accountUuid` (the `id`, `accUuid`, or `accountUuid` from `list_accounts`) plus exactly one of `amountDebit` or `amountCredit` (decimal numbers as strings or numbers — never both on the same line, never neither). Optional per-line: `descriptionLine`. Optional top-level: `refNumber`, `withCaution: true` to skip book-closeness checks (use sparingly). The server validates each account exists in this workspace before posting; manual entries can fail if any line\'s posting date falls within a reconciled period for that account.',
    method: 'POST',
    pathTemplate: '/partners/journal-entries',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_bulk_create_journal_entries',
    title: 'Bulk Create Journal Entries',
    description:
      'Create up to 100 manual journal entry postings in a single call. Body: `{ "journalEntries": [<posting>, ...] }` where each `<posting>` uses the EXACT same shape as `COUNT_create_journal_entry` (required `descriptionEntry`, `date`, `lines`; each line needs `accountUuid` + exactly one of `amountDebit` / `amountCredit`; optional per-line `descriptionLine`; optional top-level `refNumber`, `withCaution`). **Partial-success contract**: each posting runs in its own DB transaction; one bad posting never rolls back another posting\'s writes. Response envelope: `{ "successCount": N, "errorCount": M, "results": [{ "index": 0, "success": true, "journalEntry": [...lines] } | { "index": 1, "success": false, "error": "..." }, ...] }` — read `errorCount` first; if non-zero, iterate `results` and only retry the postings where `success: false`. The HTTP status is always `201` when the batch was accepted, even if all postings failed. **Cap**: 100 postings per call (split larger imports into multiple calls). **Recommended batch size**: ~25 postings for large historical imports; larger batches increase timeout risk. **Performance note**: account UUIDs are resolved in a SINGLE batched lookup across the whole batch, so a 100-posting × 10-line request issues one account query — bulk is strictly cheaper than calling `COUNT_create_journal_entry` 100 times. **Use cases**: replay manual postings from another GL, backfill accruals, ingest a CSV of journal entries. For a single posting, prefer `COUNT_create_journal_entry` — the response shape is simpler.',
    method: 'POST',
    pathTemplate: '/partners/journal-entries/bulk',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_journal_entry',
    title: 'Update Journal Entry',
    description:
      'Update a manually-created journal entry by external UUID. PATCH accepts partial bodies — send only the fields you want to change (`descriptionEntry`, `date`, `refNumber`, and/or the full replacement `lines` array). When `lines` is included, each line takes `accountUuid` and exactly one of `amountDebit`/`amountCredit`. Only manually-created entries (and Square integration entries) can be updated; system-generated journal entries from invoices, bills, payroll, etc. are read-only and return 400.',
    method: 'PATCH',
    pathTemplate: '/partners/journal-entries/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_journal_entry',
    title: 'Delete Journal Entry',
    description: 'Delete a journal entry by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/journal-entries/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_tasks',
    title: 'List Tasks',
    description:
      'List tasks for the authenticated workspace. `query` filters that accept comma-separated tokens where each token is EITHER an external UUID OR a workspace-scoped numeric id (partner middleware resolves both): `statusId` (task statuses), `assigneeId` / `assignerId` / `createdById` (workspace user references), `projects` (project filter), `commentId` (single token only — passing multiple returns 400). Pass-through filters: `page`, `limit`, `orderBy`, `orderDirection`, `search` (ILIKE on task name), `customId`, `visibility` (`"firm-team"` | `"team-only"` | `"firm-only"` — defaults to `["firm-team","team-only"]` when omitted), `priority`, `overduesOnly`, `deadlineDate` / `createdAt` / `updatedAt` (date windows), `status` (string `task.status` column). The legacy filters `clients`, `openTaskOnly`, and `isForClosing` are always stripped server-side. Numeric internal foreign keys are removed from response rows.',
    method: 'GET',
    pathTemplate: '/partners/tasks',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_task',
    title: 'Get Task',
    description:
      'Get a single task by external UUID. Default visibility is `["firm-team","team-only"]`; tasks created with `firm-only` visibility (notably system-generated INTERNAL_TASK rows) return 404 unless you explicitly pass `visibility=firm-only` under `query`.',
    method: 'GET',
    pathTemplate: '/partners/tasks/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_task',
    title: 'Create Task',
    description:
      'Create a task. Required body: `type` (string — the task type identifier). The following optional FK fields each accept EITHER an external UUID OR a workspace-scoped numeric id (partner middleware resolves both and verifies workspace scope): `assigneeId`, `statusId`, `onCompleteStatusId`, `onCompleteAssigneeId`, `projectId`, `billId`, `transactionId`, `taskListId`, `taskListTemplateId`. Other safe body fields: `name`, `description`, `priority`, `deadline` (YYYY-MM-DD), `customId`, `visibility`. `tags` accepts an array OR a JSON-encoded string — every element must be the same kind (all UUIDs or all positive integer ids); mixed inputs return 400. If `assigneeId` is omitted it defaults to the partner-acting user. INTERNAL_TASK rows are always created with `firm-only` visibility regardless of the `visibility` value you pass. The partner endpoint is JSON-only — multipart attachments are not supported.',
    method: 'POST',
    pathTemplate: '/partners/tasks',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_task',
    title: 'Update Task',
    description:
      'Update a task by external UUID. Pass only the fields you want to change; the same body shape as `create_task` applies. `tags` accepts either an array or a JSON-encoded string and replaces all tags atomically. UUID-resolvable optional FKs: `assigneeId`, `statusId`, `onCompleteStatusId`, `onCompleteAssigneeId`, `projectId`, `billId`, `transactionId`, `taskListId`, `taskListTemplateId` — each accepts a UUID or a workspace-scoped numeric id.',
    method: 'PATCH',
    pathTemplate: '/partners/tasks/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_task',
    title: 'Delete Task',
    description: 'Delete a task by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/tasks/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_projects',
    title: 'List Projects',
    description:
      'List projects for the authenticated workspace. Soft-deleted projects are always excluded. `query` filters: `page` (default 1), `limit` (default 20), `search` (ILIKE on project name), `customerUuids` (comma-separated customer UUIDs — partner middleware resolves these into the internal `customers` filter), and `statusUuids` (comma-separated project-status UUIDs — discover them via `list_project_statuses`). The internal `customers`, `statusIds`, and `status` filters are stripped server-side; only the `*Uuids` variants take effect.',
    method: 'GET',
    pathTemplate: '/partners/projects',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_project_statuses',
    title: 'List Project Statuses',
    description:
      'List the project statuses available in the authenticated workspace. Returns each status with its name, color, ordering, and external UUID — use the returned UUID as `statusUuid` on `create_project` / `update_project`, or in `statusUuids` (CSV) on `list_projects`.',
    method: 'GET',
    pathTemplate: '/partners/projects/statuses',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_project',
    title: 'Get Project',
    description: 'Get a single project by external UUID. Soft-deleted projects return 404.',
    method: 'GET',
    pathTemplate: '/partners/projects/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_project_tasks',
    title: 'List Project Tasks',
    description:
      'List the tasks attached to a project by external UUID. `query` filters: `page` (default 1), `limit` (default 20), `search` (ILIKE on task name). Returns the same partner-sanitized task envelope as `list_tasks`.',
    method: 'GET',
    pathTemplate: '/partners/projects/{id}/tasks',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_project',
    title: 'Create Project',
    description:
      'Create a project. Required body: non-empty `name`. Optional body: `customerUuid` (from `list_customers`; pass `null` or omit to leave the project uncustomered), `statusUuid` (from `list_project_statuses` — defaults to the workspace\'s default status if omitted), plus any safe project columns (e.g. `description`, `customId`, `startDate`, `endDate`). The numeric internal FKs `customerId`, `statusId`, and `teamId` are always stripped before the request is processed — use the `*Uuid` variants instead.',
    method: 'POST',
    pathTemplate: '/partners/projects',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_project',
    title: 'Update Project',
    description:
      'Update a project by external UUID. Pass only the fields you want to change. `customerUuid` accepts a UUID (set the customer), `null`/`""` (clear the customer), or omission (leave unchanged). `statusUuid` accepts a UUID (set the status) or omission (leave unchanged). The numeric `customerId`, `statusId`, and `teamId` fields are stripped server-side. If you pass `customId` matching the existing value it may be discarded silently.',
    method: 'PATCH',
    pathTemplate: '/partners/projects/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_project',
    title: 'Delete Project',
    description: 'Delete a project by external UUID (soft delete).',
    method: 'DELETE',
    pathTemplate: '/partners/projects/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_list_time_entries',
    title: 'List Time Entries',
    description:
      'List time entries for the authenticated workspace. Soft-deleted entries are always excluded. `query` filters: `page` (default 1), `limit` (default 50), and the comma-separated UUID filters `peopleUuids`, `projectUuids`, `customerUuids`, `productServiceUuids` (each resolved into its internal numeric filter by the partner middleware). Direct numeric filters (`people`, `projects`, `customers`, `productServices`) are stripped server-side; only the `*Uuids` variants take effect. Date window filter: both `startDate` AND `endDate` (YYYY-MM-DD) must be provided together for the `createdAt`-range filter to apply — passing only one is ignored.',
    method: 'GET',
    pathTemplate: '/partners/time-entries',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_time_entry',
    title: 'Get Time Entry',
    description: 'Get a single time entry by external UUID. Soft-deleted entries return 404.',
    method: 'GET',
    pathTemplate: '/partners/time-entries/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_time_entry',
    title: 'Create Time Entry',
    description:
      'Create one or more time entry rows. Required body: `peopleUuid` (from `list_people` — must be present and non-empty on create; partner middleware resolves it into the internal `peopleId`) and `timeEntries: [{ date: "YYYY-MM-DD", minutes: <integer>, ... }]` (array of row objects). Per-row optional fields: `description`, `projectUuid` (resolves to the project; setting it auto-fills the matching customer), `customerUuid`, `productServiceUuid`, `billable`, `wage`. Daily cap: the sum of `minutes` across entries on the same calendar day for the same person cannot exceed 24h — the server returns 400 with the remaining-minutes if exceeded. The numeric `peopleId`, `projectId`, `customerId`, `productServiceId`, and `teamId` fields are stripped server-side; use the `*Uuid` variants.',
    method: 'POST',
    pathTemplate: '/partners/time-entries',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_time_entry',
    title: 'Update Time Entry',
    description:
      'Update a time entry by external UUID. Pass only the fields you want to change. `peopleUuid` cannot be cleared on update (passing `null`/`""` returns 400). `projectUuid` / `customerUuid` / `productServiceUuid` each accept a UUID (set) or `null` (clear). Time entries that belong to a processed pay period are read-only and return 400.',
    method: 'PATCH',
    pathTemplate: '/partners/time-entries/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_time_entry',
    title: 'Delete Time Entry',
    description:
      'Delete a time entry by external UUID (soft delete). Time entries that belong to a processed pay period cannot be deleted and return 400 — adjust the pay period first.',
    method: 'DELETE',
    pathTemplate: '/partners/time-entries/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  // All three report endpoints are POST + read-only for MCP: report filters
  // live on the **query** object, and MCP exposes only generated report output.
  // This keeps the tool annotations truthful for Claude connector review.
  {
    name: 'COUNT_list_expense_receipts',
    title: 'List Expense Receipts',
    description: 'List expense receipts (pending receipts) for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/expense-receipts',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_unmatched_expense_receipts',
    title: 'List Unmatched Expense Receipts',
    description: 'List unmatched expense receipts (pending receipts) for the authenticated COUNT workspace.',
    method: 'GET',
    pathTemplate: '/partners/expense-receipts/unmatched',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_expense_receipt',
    title: 'Create Expense Receipt',
    description:
      'Create an expense receipt (pending receipt). MCP forwards JSON only; to attach a receipt image call the partner HTTP API directly as multipart/form-data with field `receipt`. Partner bodies use UUID fields such as accountUuid, categoryAccountUuid, optional expenseReportTypeUuid, vendorUuid, projectUuid, tagUuids, taxUuids — see COUNT Partner API docs. API responses omit receiptUrl by design.',
    method: 'POST',
    pathTemplate: '/partners/expense-receipts',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_update_expense_receipt',
    title: 'Update Expense Receipt',
    description:
      'Update an expense receipt by external UUID. MCP forwards JSON only; to replace the receipt image use multipart field `receipt` on the partner HTTP API.',
    method: 'PATCH',
    pathTemplate: '/partners/expense-receipts/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_delete_expense_receipt',
    title: 'Delete Expense Receipt',
    description: 'Delete an unmatched expense receipt by external UUID.',
    method: 'DELETE',
    pathTemplate: '/partners/expense-receipts/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_match_expense_receipt_manually',
    title: 'Match Expense Receipt Manually',
    description:
      'Match an expense receipt to an expense transaction. Body uses transactionUuid (COUNT transaction external UUID).',
    method: 'POST',
    pathTemplate: '/partners/expense-receipts/{id}/match-manually',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_unmatch_expense_receipt',
    title: 'Unmatch Expense Receipt',
    description: 'Unmatch an expense receipt from its linked transaction.',
    method: 'DELETE',
    pathTemplate: '/partners/expense-receipts/{id}/unmatch',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_generate_trial_balance',
    title: 'Generate Trial Balance',
    description:
      'Generate a trial balance for the authenticated workspace. Put filters under `query`: `endDate` (required, YYYY-MM-DD — the as-of date), `startDate` (optional, defaults to fiscal-year start), `currency` (defaults to workspace currency), `transactionStatus` ("all" | "reviewed" | "unreviewed" | "reconciled" | "unreconciled"), `accounts` or `accountUuids` (comma-separated account UUIDs from `list_accounts` — do NOT pass internal numeric ids), `tags` or `tagUuids` (comma-separated tag UUIDs from `list_tags`), `noTags: "true"` (only entries with no tags), `accountType` (one of "Assets", "Liabilities", "Equity", "Income", "Expenses"). This MCP tool is read-only; no `body` is accepted.',
    method: 'POST',
    pathTemplate: '/partners/reports/trial-balance',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_generate_profit_and_loss',
    title: 'Generate Profit And Loss',
    description:
      'Generate a P&L (income statement) for the authenticated workspace. Put filters under `query`: required `startDate` and `endDate` (YYYY-MM-DD); optional `currency`, `transactionStatus` ("all" | "reviewed" | "unreviewed" | "reconciled" | "unreconciled"), `categoryAccount`, `categoryAccountUuid`, or `categoryAccountUuids` (comma-separated account UUIDs from `list_accounts` — use this to filter to one or more income/expense categories such as "Freight & Courier"; do NOT pass internal numeric ids), `tags` or `tagUuids`, `customers` or `customerUuids`, `vendors` or `vendorUuids`, `projects` or `projectUuids`, `products` or `productUuids`, `isPnLByTag: true` (column-per-tag breakdown), `includeNoTag: true`, `reportYear` ("financial" | "calendar"). This MCP tool is read-only; no `body` is accepted. **Sign convention**: revenue rows are returned as positive amounts and expense rows as negative; net profit is the algebraic sum.',
    method: 'POST',
    pathTemplate: '/partners/reports/pnl',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_generate_balance_sheet',
    title: 'Generate Balance Sheet',
    description:
      'Generate a balance sheet for the authenticated workspace. Put filters under `query`: required `endDate` (YYYY-MM-DD — the as-of date); optional `startDate` (used as the prior-period comparison anchor), `currency`, `transactionStatus`, `accounts` or `accountUuids` (comma-separated account UUIDs from `list_accounts` — do NOT pass internal numeric ids), `tags` or `tagUuids`. This MCP tool is read-only; no `body` is accepted. Returns Assets / Liabilities / Equity sections with subtotals; the report fails to balance only when there are unposted manual entries — those are surfaced in the response payload.',
    method: 'POST',
    pathTemplate: '/partners/reports/balance-sheet',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },

  // ---------------- Budgets ----------------
  {
    name: 'COUNT_list_budgets',
    title: 'List Budgets',
    description:
      'List P&L budgets for the authenticated workspace. Optional `query.status`: `draft`, `published`, or `archived`. Each budget returns its external UUID as `id`, metadata (name, startPeriod, cadence, actualPeriods, budgetPeriods, currencyCode, status, isOverall), and version summaries (versionNumber, label, isPublished).',
    method: 'GET',
    pathTemplate: '/partners/budgets',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_get_overall_budget',
    title: 'Get Overall Budget',
    description:
      'Get the workspace Overall Budget (if configured). Returns the same budget object shape as `list_budgets` rows, or null when no overall budget exists.',
    method: 'GET',
    pathTemplate: '/partners/budgets/overall',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_create_budget',
    title: 'Create Budget',
    description:
      'Create a draft budget and seed P&L budget lines for every active Income/Expenses account. Required body: `name`, `startPeriod` (YYYY-MM-DD), `cadence` (`monthly` | `yearly`), `actualPeriods` (>= 0), `budgetPeriods` (>= 1). Optional: `currencyCode` (defaults to workspace currency), `isOverall` (boolean — only one overall budget per workspace). Returns `{ budget, version }` with the initial versionNumber (usually 1). After create, import amounts with `bulk_update_budget_cells`.',
    method: 'POST',
    pathTemplate: '/partners/budgets',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_get_budget',
    title: 'Get Budget',
    description: 'Get a single budget by external UUID, including version summaries.',
    method: 'GET',
    pathTemplate: '/partners/budgets/{id}',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_update_budget',
    title: 'Update Budget',
    description:
      'Update draft budget metadata by external UUID. Pass only fields to change: `name`, `startPeriod`, `cadence`, `actualPeriods`, `budgetPeriods`, `isOverall`. Rejected when the budget is published or locked.',
    method: 'PATCH',
    pathTemplate: '/partners/budgets/{id}',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_get_budget_grid',
    title: 'Get Budget Grid',
    description:
      'Export a budget grid for Excel round-trips. Returns `columns` (actual + budget period labels) and `rows` with `accountUuid`, `accountName`, `accountPath`, and per-period `values`. Optional `query.versionNumber` (defaults to latest version), `query.reportType` (`accrual` | `cash`), and `query.includeActuals` (`false` skips journal-entry actuals for faster budget-only export). Use `list_accounts` / `resolve_references` to map account names before re-importing edited rows.',
    method: 'GET',
    pathTemplate: '/partners/budgets/{id}/grid',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_list_budget_versions',
    title: 'List Budget Versions',
    description:
      'List version summaries for a budget: `versionNumber`, `label`, `isPublished`, `createdAt`. Use `versionNumber` on cell update tools.',
    method: 'GET',
    pathTemplate: '/partners/budgets/{id}/versions',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
  {
    name: 'COUNT_update_budget_cells',
    title: 'Update Budget Cells',
    description:
      'Atomically update up to 100 budget cell amounts on a **draft** version. Requires `id` (budget UUID) and `versionNumber`. Body: `{ updates: [{ accountUuid, periodStart (YYYY-MM-DD), amount }] }`. Each row must reference a P&L account UUID from `list_accounts` and a budget column periodStart from `get_budget_grid`. All rows succeed or fail together.',
    method: 'PATCH',
    pathTemplate: '/partners/budgets/{id}/versions/{versionNumber}/cells',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_bulk_update_budget_cells',
    title: 'Bulk Update Budget Cells',
    description:
      'Import budget amounts with partial-success semantics (recommended for spreadsheet imports). Same row shape as `update_budget_cells`: `{ updates: [{ accountUuid, periodStart, amount }, ...] }`. **Cap**: 100 rows per call; **recommended batch size**: ~25. Response: `{ successCount, errorCount, results: [{ index, success, budgetCellUpdate? | error }] }`. HTTP status is `201` when the batch is accepted even if some rows fail — retry only failed indices.',
    method: 'POST',
    pathTemplate: '/partners/budgets/{id}/versions/{versionNumber}/cells/bulk',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_create_budget_version',
    title: 'Create Budget Version',
    description:
      'Create a new draft budget version (copies lines and cell values from the previous version). Optional body: `label`. Returns the new version with an incremented `versionNumber`.',
    method: 'POST',
    pathTemplate: '/partners/budgets/{id}/versions',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_publish_budget',
    title: 'Publish Budget',
    description:
      'Publish a budget version and set budget status to `published`. Optional body: `versionNumber` (defaults to latest draft). Rejects cell edits on published versions.',
    method: 'POST',
    pathTemplate: '/partners/budgets/{id}/publish',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },
  {
    name: 'COUNT_archive_budget',
    title: 'Archive Budget',
    description: 'Archive a budget by external UUID. Cannot archive the Overall Budget.',
    method: 'POST',
    pathTemplate: '/partners/budgets/{id}/archive',
    requiresUserAuth: true,
    readOnly: false,
    destructive: true,
  },
  {
    name: 'COUNT_duplicate_budget',
    title: 'Duplicate Budget',
    description:
      'Duplicate a budget into a new draft. Required body: `newName`. Optional: `carryValues` (copy cell amounts), `isOverall`, `versionNumber` (source version; defaults to latest).',
    method: 'POST',
    pathTemplate: '/partners/budgets/{id}/duplicate',
    requiresUserAuth: true,
    readOnly: false,
    destructive: false,
  },

  // ---------------- Workspace Stats (aggregated business snapshot) ----------------
  {
    name: 'COUNT_get_workspace_stats',
    title: 'Get Workspace Stats',
    description:
      'Aggregated business snapshot for the authenticated workspace — the one-stop call for a CFO-style dashboard. Returns:\n' +
      '- `workspace`: identity + accounting basis (name, currency, country, industry, fiscalYearMonth, dateFormat, cutoverDate, reportType, `bookClosedThroughDate`).\n' +
      '- `cash`: `currentCash` (Cash & Bank + Credit Cards across provider, reconciliation, and COUNT-book sources — credit-card debt subtracts from cash), `bankAndCashAssetsTotal`, `creditCardLiabilitiesTotal`, `accountSourceCounts` (how many accounts contributed via each source), `staleProviderBalanceAccountCount` (provider balances older than 24h), `currentCashAsOf`.\n' +
      '- `profitability`: `currentMonth`, `currentQuarter`, `yearToDate`, `trailingTwelveMonths`, `priorYearSamePeriod` each as `{ revenue, expenses, netProfit, startDate, endDate }`. Sign convention: revenue and expenses are both positive numbers; `netProfit = revenue - expenses`. Plus `rollingThreeMonths` with monthly averages, `netBurn`, and `runwayMonths` (null when not burning).\n' +
      '- `receivables`: `totalOutstanding`, `currentDueTotal`, `overdueTotal`, `overdueCount`, `agingBuckets` (notYetOverdue/lessThanOrEqualTo30/between31And60/between61And90/moreThan90), `oldestOutstandingDate`, `topCustomersOutstanding[]` (with COUNT customer UUIDs), `daysSalesOutstanding`.\n' +
      '- `payables`: same shape as receivables for vendors, plus `outstandingBills` (gross document-side unpaid total), `dueInNext7Days`, `dueInNext30Days`, and `daysPayableOutstanding`.\n' +
      '- `taxObligations`: `isTaxRegistered`, `taxRegime` (`"NZ_GST"` or null), `totalObligation` (positive = owed to IRD, negative = refund), `hasOverdueOrUpcomingFiling`, `obligations[]` (per period with status + dueDate), `lastFiledPeriodEnd`. `irdAuthorizationFailed` set when IRD auth is stale.\n' +
      '- `connections`: `totalCount`, `activeCount`, `disconnectedCount`, `revokedCount`, `accountsAwaitingReauthCount`, `staleConnectionCount24h`, `oldestLastSyncAt`, `byProvider`.\n' +
      '- `asOf`: `computedAt`, `cacheTtlSeconds`, `cashAsOf`, `currency`, `fromCache` (true when this response came from the 5-minute Redis cache).\n\n' +
      'Optional `query.include` is a comma-separated list of blocks to compute (omit any block you do not need): `workspace,cash,profitability,receivables,payables,taxObligations,connections`. Omitting `include` returns every block. This is the cheapest single call to populate an end-of-period dashboard or a "how is the business doing right now" summary.',
    method: 'GET',
    pathTemplate: '/partners/workspace-stats',
    requiresUserAuth: true,
    readOnly: true,
    destructive: false,
  },
];

const tools: ToolDefinition[] = rawTools.map((_tool) => ({
  ..._tool,
  inputSchema: toolInputSchemas.getToolInputSchema({ toolName: _tool.name }),
}));

export const toolDefinitions = tools;

interface GetToolDefinitionParams {
  toolName: string;
}

export function getToolDefinition(params: GetToolDefinitionParams): ToolDefinition | undefined {
  const { toolName } = params;
  return toolDefinitions.find((_tool) => _tool.name === toolName);
}

